### ISSUE TITLE
Expected end of line, etc. but found identifier.

### ISSUE THREAD

**Issue by LoganDark** [jeroenbegyn/VLCControl#1] opened 2018-07-01 05:59 UTC
`osascript` output:
```
1 LoganDark ~ osascript ~/VLCControl/VLCControl.scpt
/Users/LoganDark/VLCControl/VLCControl.scpt:1214:1219: script error: Expected end of line, etc. but found identifier. (-2741)
```
`osacompile` output:
```
/Users/LoganDark/VLCControl/VLCControl.scpt:31: error: Expected end of line, etc. but found identifier. (-2741)
```

**Comment by jeroenbegyn** [comment] 2023-11-11 22:47
Which version of OSX are you using? I can't seem to reproduce this issue.

**Comment by LoganDark** [comment] 2023-11-11 22:49
This issue was reported over five years ago. I believe I was on macOS High Sierra at the time, but I don't have easy access to a Mac anymore.

**Comment by jeroenbegyn** [comment] 2023-11-11 23:11
Ok, I'll close this issue since I can't reproduce.

**Closed as not planned by jeroenbegyn** 2023-11-11 23:11 UTC
